# Generated by Django 4.2.2 on 2023-07-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionistprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registeredcustomerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Receptionist',
        ),
        migrations.DeleteModel(
            name='RegisteredCustomer',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='ReceptionistProfile',
        ),
        migrations.DeleteModel(
            name='RegisteredCustomerProfile',
        ),
    ]
