# Generated by Django 4.2.2 on 2023-08-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_rename_user_id_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='special_info',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
