# Generated by Django 4.2.2 on 2023-07-11 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_reservation_room_id_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='garden.room'),
        ),
    ]
