# Generated by Django 4.2.2 on 2023-07-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_remove_customer_street_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('cardno', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='credit_card')),
                ('expmonth', models.CharField(max_length=2)),
                ('expyear', models.CharField(max_length=2)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
    ]
