# Generated by Django 4.2.2 on 2023-07-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_alter_room_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='amenity_description',
        ),
    ]
