# Generated by Django 4.2.2 on 2023-07-12 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_alter_reservation_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='garden.room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='garden.room'),
        ),
    ]
