# Generated by Django 4.2.2 on 2023-07-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_remove_amenities_amenity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.ImageField(default='default_room_image_twr44l.jpg', upload_to='garden_room_images/'),
        ),
    ]
