# Generated by Django 4.2.2 on 2023-07-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_alter_amenities_room_id_alter_reservation_room_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenities',
            options={'verbose_name_plural': 'amenities'},
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='room_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='garden.customer'),
        ),
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('room_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='garden.room')),
                ('amenity_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='garden.amenities')),
            ],
            options={
                'unique_together': {('room_id', 'amenity_id')},
            },
        ),
    ]
