# Generated by Django 4.2.2 on 2023-07-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_alter_amenities_options_remove_amenities_room_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='adults',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='children',
            field=models.CharField(max_length=20),
        ),
    ]
