# Generated by Django 4.2.2 on 2023-07-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_remove_user_address_remove_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='def', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='def_city', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='def_country', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='07xxxxxxxx', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='def_state', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default='xxxxxx', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
